version: '2'

services:
  db:
    image: postgres
  app:
    build: .
    command: "./entry_point.sh"
    restart: always
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
