version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./entry_point.sh"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
