version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./entry_point.sh"
    volumes:
      - .:/src/volume
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
