version: '2'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    command: "./entry_point.sh"
    restart: always
    volumes:
      - .:/src/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
